name: documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        working-directory: ./jakenelson.cloud
        with:
          node-version: '12.x'
      - name: Test Build
        working-directory: ./jakenelson.cloud
        run: |
          yarn build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        working-directory: ./jakenelson.cloud
        with:
          node-version: '12.x'
      - name: Release to GitHub Pages
        working-directory: ./jakenelson.cloud
        run: |
          git config --global user.email "jakesmnelson@gmail.com"
          git config --global user.name "Jake-Mok-Nelson"
          GIT_USER=Jake-Mok-Nelson yarn deploy
