name: publish-site

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATEKEY }}
      - name: Get Dependencies
        run: |
          yarn --cwd ./jakenelson.cloud/ install
      - name: Build
        run: |
          yarn --cwd ./jakenelson.cloud/ build
      - name: Publish to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: Jake-Mok-Nelson
        run: |
          git config --global user.email "jakesmnelson@gmail.com"
          git config --global user.name "Jake-Mok-Nelson"
          yarn --cwd ./jakenelson.cloud/ deploy
