name: publish-site

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name Jake-Mok-Nelson
          git config user.email jakesmnelson@gmail.com
          make GH_TOKEN=$GH_TOKEN deploy
