name: publish-site

on:
  push:
    branches:
      - main
    paths:
      - jakenelson.cloud/**

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
#       - uses: webfactory/ssh-agent@v0.5.0
#         with:
#           ssh-private-key: ${{ secrets.PRIVATEKEY }}
      - name: Build
        run: |
          yarn --cwd ./jakenelson.cloud/ install
          yarn --cwd ./jakenelson.cloud/ build
      - name: Docusaurus BuildDeploy Action
        # You may pin to the exact commit or the version.
        # uses: redkubes/docusaurus-deploy-action@f81b409203e9562ebbac672e37daa5e8a6193144
        uses: redkubes/docusaurus-deploy-action@master
        with:
          # source folder
          source-folder: jakenelson.cloud
          # git user name
          git-user: Jake-Mok-Nelson
          # git password (defaults to secrets.GITHUB_TOKEN, which should work if it has default rights)
          git-password: ${{ secrets.GITHUB_TOKEN }}
          # git branch to publish to (defaults to gh-pages)
          # deployment-branch: # optional
