name: test-site

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: |
          yarn --cwd ./jakenelson.cloud/ install
      - name: Build
        run: |
          yarn --cwd ./jakenelson.cloud/ build
